site_name: aiotieba
site_description: aiotieba开发文档
site_url: https://aiotieba.cc/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
  language: zh

repo_name: Starry-OvO/aiotieba
repo_url: https://github.com/Starry-OvO/aiotieba/

nav:
  - 介绍: index.md
  - 教程:
      - 入门教程: tutorial/start.md
      - 异步编程入门教程: tutorial/async_start.md
      - 配置文件参考: tutorial/config.md
      - 实用微脚本合集: tutorial/many_utils.md
  - 参考文档:
      - 客户端 (Client): ref/client.md
      - 枚举定义: ref/enums.md
      - 类型定义:
          - forum_detail: ref/classdef/forum_detail.md
          - threads: ref/classdef/threads.md
          - posts: ref/classdef/posts.md
          - comments: ref/classdef/comments.md
          - searches: ref/classdef/searches.md
          - user_info: ref/classdef/user_info.md
          - profile: ref/classdef/profile.md
          - follows: ref/classdef/follows.md
          - fans: ref/classdef/fans.md
          - blacklist: ref/classdef/blacklist.md
          - blacklist_old: ref/classdef/blacklist_old.md
          - follow_forums: ref/classdef/follow_forums.md
          - self_follow_forums: ref/classdef/self_follow_forums.md
          - dislike_forums: ref/classdef/dislike_forums.md
          - user_contents: ref/classdef/user_contents.md
          - replys: ref/classdef/replys.md
          - ats: ref/classdef/ats.md
          - square_forums: ref/classdef/square_forums.md
          - bawu_info: ref/classdef/bawu_info.md
          - god_threads: ref/classdef/god_threads.md
          - rank_users: ref/classdef/rank_users.md
          - member_users: ref/classdef/member_users.md
          - blocks: ref/classdef/blocks.md
          - recovers: ref/classdef/recovers.md
          - bawu_userlogs: ref/classdef/bawu_userlogs.md
          - bawu_postlogs: ref/classdef/bawu_postlogs.md
          - unblock_appeals: ref/classdef/unblock_appeals.md
          - bawu_blacklist: ref/classdef/bawu_blacklist.md
          - statistics: ref/classdef/statistics.md
          - recom_status: ref/classdef/recom_status.md
          - group_msg: ref/classdef/group_msg.md

markdown_extensions:
  - md_in_html
  - admonition
  - codehilite:
      css_class: highlight

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_bases: false
            show_source: false
            members_order: source

extra_css:
  - css/custom.css
