site_name: aiotieba
site_description: aiotieba开发文档
site_url: https://v-8.top/

theme:
  name: material
  features:
    - navigation.sections
  language: zh

repo_name: Starry-OvO/aiotieba
repo_url: https://github.com/Starry-OvO/aiotieba

nav:
    - 介绍: index.md
    - 教程:
      - 快速入门: tutorial/quickstart.md
      - 爬虫教程: tutorial/crawler.md
      - 云审查教程: tutorial/reviewer.md
      - 指令管理器使用教程: tutorial/cmd_handler_user.md
      - 指令管理器配置教程: tutorial/cmd_handler_dev.md
      - 实用微脚本合集: tutorial/many_utils.md
    - 参考文档:
      - client: ref/client.md
      - typedef: ref/typedef.md
      - enum: ref/enum.md
    - 逆向分析教程:
      - 贴吧私信接口逆向分析: misc/websocket_reverse_engineering.md

markdown_extensions:
  - md_in_html
  - admonition
  - codehilite:
      css_class: highlight

extra_css:
    - css/custom.css
